import os
import json
from openai import OpenAI
from dotenv import load_dotenv

# Load environment configuration
load_dotenv()
_api_key = os.getenv("OPENAI_API_KEY")
_openai_client = OpenAI(api_key=_api_key) if _api_key else None

def parse_triples(document_text, model_id='gpt-4o-mini'):
    """
    Invokes the OpenAI API to extract a structured list of triples (subject, relation, object).
    """
    if not _api_key:
        print("[!] Warning: OPENAI_API_KEY is not defined in the environment.")
        return []
        
    system_prompt = f"""
    You are an expert at Named Entity Recognition and Relation Extraction.
    Analyze the text below and extract all meaningful semantic triples.
    Format your response as a valid JSON array. Each element in the array must be an object with exactly three fields: "subject", "relation", and "object".
    Provide ONLY the raw JSON array. Do not include markdown code block formatting (such as ```json) or any additional explanation.
    
    Example output format:
    [
      {{"subject": "Apple", "relation": "headquartered in", "object": "Cupertino"}},
      {{"subject": "Tim Cook", "relation": "CEO of", "object": "Apple"}}
    ]

    Text to extract:
    {document_text}
    """
    
    try:
        completion = _openai_client.chat.completions.create(
            model=model_id,
            messages=[{"role": "user", "content": system_prompt}],
            temperature=0.1
        )
        raw_response = completion.choices[0].message.content.strip()
        
        # Clean up code blocks if generated by the LLM
        if raw_response.startswith("```json"):
            raw_response = raw_response[7:]
        if raw_response.startswith("```"):
            raw_response = raw_response[3:]
        if raw_response.endswith("```"):
            raw_response = raw_response[:-3]
            
        raw_response = raw_response.strip()
        
        parsed_data = json.loads(raw_response)
        if isinstance(parsed_data, list):
            return parsed_data
        return []
        
    except json.JSONDecodeError:
        print("[!] JSONDecodeError: LLM returned invalid JSON structure.")
        print(f"Truncated raw response: {raw_response[:100]}...")
        return []
    except Exception as error:
        print(f"[!] Error calling OpenAI client: {error}")
        return []

def process_corpus(docs, output_file='outputs/triples.json'):
    """
    Extracts triples from all documents in the corpus, caching results to prevent redundant API usage.
    """
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    
    # Load cached results if available
    if os.path.exists(output_file):
        print(f"[*] Loading cached relation triples from {output_file}")
        with open(output_file, 'r', encoding='utf-8') as f:
            return json.load(f)
            
    extracted_triples = []
    print(f"[*] Extracting facts from {len(docs)} documents using LLM...")
    
    for idx, doc in enumerate(docs):
        print(f"    ({idx+1}/{len(docs)}) Processing document ID: {doc['id']}")
        triples = parse_triples(doc['text'])
        # Reference source file for backtracking
        for item in triples:
            item['source_doc'] = doc['id']
        extracted_triples.extend(triples)
        
    # Cache results
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(extracted_triples, f, indent=4, ensure_ascii=False)
        
    print(f"[*] Saved {len(extracted_triples)} facts to cache file: {output_file}")
    return extracted_triples
